- name: Check if steam_home is defined.
  assert:
    that: steam_home is defined

- block:
    - name: Check if Counter-Strike Global Offensive dedicated server is installed
      stat:
        path: "{{ steam_home }}/steamapps/common/csgo-ds"
      register: __cstrikego_exists

    - name: Install Counter-Strike Global Offensive dedicated server
      command: "{{ steamcmd_bin }} +login anonymous +app_update 740 +validate +quit"
      when: not __cstrikego_exists.stat.exists

    - name: Ensure Counter-Strike Global Offensive dedicated server is up to date
      command: "{{ steamcmd_bin }} +login anonymous +app_update 740 +quit"
      register: __cstrikego_update
      changed_when: "'already up to date' not in __cstrikego_update.stdout"
      when: __cstrikego_exists.stat.exists
  become_user: "{{ steamcmd_user }}"

- name: Create a symlink to steam home directory
  file:
    src: "{{ steam_home }}/steamapps/common/csgo-ds"
    dest: "/home/{{ steamcmd_user }}/csgo-ds"
    owner: "{{ steamcmd_user }}"
    group: "{{ steamcmd_user }}"
    state: link

- name: Ensure motd.txt is installed
  template:
    dest: "/home/{{ steamcmd_user }}/csgo-ds/cstrike/cfg/motd.txt"
    src: motd.txt.j2
    owner: "{{ steamcmd_user }}"
    group: "{{ steamcmd_user }}"
  notify: Restart csgo-ds

- name: Ensure mapcycle.txt is installed
  template:
    dest: "/home/{{ steamcmd_user }}/csgo-ds/cstrike/cfg/mapcycle.txt"
    src: mapcycle.txt.j2
    owner: "{{ steamcmd_user }}"
    group: "{{ steamcmd_user }}"
  notify: Restart csgo-ds

- name: Ensure server.cfg is installed
  template:
    dest: "/home/{{ steamcmd_user }}/csgo-ds/cstrike/cfg/server.cfg"
    src: server.cfg.j2
    owner: "{{ steamcmd_user }}"
    group: "{{ steamcmd_user }}"
  notify: Restart csgo-ds

- block:
    - name: Ensure extra mapcycle files are installed
      template:
        dest: "/home/{{ steamcmd_user }}/csgo-ds/cstrike/cfg/mapcycle_{{ item.name }}.txt"
        src: extra_mapcycle.txt.j2
        owner: "{{ steamcmd_user }}"
        group: "{{ steamcmd_user }}"
      loop: "{{ cstrike_go_extra_mapcycles }}"
      loop_control:
        label: "{{ item.name }}"
      when: 'item.state is not defined or item.state != "absent"'

    - name: Ensure unwanted mapcycle files are deleted
      file:
        path: "/home/{{ steamcmd_user }}/csgo-ds/cstrike/cfg/mapcycle_{{ item.name }}.txt"
        state: absent
      loop: "{{ cstrike_go_extra_mapcycles }}"
      loop_control:
        label: "{{ item.name }}"
      when: 'item.state is defined and item.state == "absent"'
  when: 'cstrike_go_extra_mapcycles != []'

- name: Ensure extra maps are installed
  synchronize:
    src: "{{ cstrike_go_extra_maps_directory }}/{{ item }}"
    dest: "/home/{{ steamcmd_user }}/csgo-ds/cstrike/custom/ansible"
  loop:
    - maps
    - materials
    - rego
  when: 'cstrike_go_extra_maps_directory != ""'

- name: Ensure systemd unit is installed
  template:
    src: csgo-ds.service.j2
    dest: /etc/systemd/system/csgo-ds.service
  notify: Reload systemd

- meta: flush_handlers

- name: Ensure csgo-ds is enabled at boot
  service:
    name: csgo-ds
    enabled: yes

- name: Ensure csgo-ds is started
  service:
    name: csgo-ds
    state: started