- name: Reload systemd
  systemd:
    daemon_reload: yes

- name: Restart source game
  service:
    name: csgo
    state: restarted
  listen: "Restart source games"

- name: Stop source game
  service:
    name: csgo
    state: stopped
  listen: "Stop source games"